name: Update GitHub Stats Daily

on:
  schedule:
    - cron: '0 18 * * *'    # chạy mỗi ngày lúc 1h sáng giờ Việt Nam
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate stats cards
        run: |
          curl -s "https://github-readme-stats.vercel.app/api?username=macqdung&show_icons=true&include_all_commits=true&count_private=true&theme=tokyonight&hide_border=true&bg_color=0D1117&title_color=58A6FF&icon_color=58A6FF&cache_seconds=86400" -o stats.svg
          curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=macqdung&layout=compact&langs_count=8&theme=tokyonight&hide_border=true&bg_color=0D1117&title_color=58A6FF&cache_seconds=86400" -o top-langs.svg
          
      - name: Commit SVG files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update github stats"
          file_pattern: "*.svg"
